credentials:
  usernames:
    jdoe:
      email: john.doe@mail.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: "John Doe"
      role: "Center A"
      password: password # Will be hashed automatically
    mdupont:
      email: mr.dupont@mail.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: "Mr Dupont"
      role: "Center B"
      password: password # Will be hashed automatically
cookie:
  expiry_days: 30
  key: some_key # Must be string
  name: some_cookie_name